CREATE TABLE `after_sale_request` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `request_no` VARCHAR(64) NOT NULL,
    `order_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `request_type` VARCHAR(32) NOT NULL,
    `reason` VARCHAR(255) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `previous_order_status` INT NOT NULL,
    `reviewed_by` BIGINT DEFAULT NULL,
    `review_reason` VARCHAR(255) DEFAULT NULL,
    `reviewed_at` DATETIME DEFAULT NULL,
    `refund_no` VARCHAR(64) DEFAULT NULL,
    `active_order_id` BIGINT GENERATED ALWAYS AS
        (CASE WHEN `status` IN ('PENDING', 'APPROVED', 'REFUND_PROCESSING', 'REFUND_FAILED') THEN `order_id` ELSE NULL END),
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_after_sale_request_no` (`request_no`),
    UNIQUE KEY `uk_after_sale_active_order` (`active_order_id`),
    KEY `idx_after_sale_user_time` (`user_id`, `create_time`),
    KEY `idx_after_sale_status_time` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='取消与售后申请';

CREATE TABLE `refund_transaction` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `refund_no` VARCHAR(64) NOT NULL,
    `business_key` VARCHAR(128) NOT NULL,
    `order_id` BIGINT NOT NULL,
    `payment_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `source_account_id` BIGINT NOT NULL,
    `target_account_id` BIGINT NOT NULL,
    `amount_cent` BIGINT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `attempt_count` INT NOT NULL DEFAULT 0,
    `freeze_transfer_id` BIGINT DEFAULT NULL,
    `release_transfer_id` BIGINT DEFAULT NULL,
    `gateway_refund_no` VARCHAR(128) DEFAULT NULL,
    `failure_code` VARCHAR(64) DEFAULT NULL,
    `failure_message` VARCHAR(255) DEFAULT NULL,
    `succeeded_at` DATETIME DEFAULT NULL,
    `next_retry_at` DATETIME DEFAULT NULL,
    `version` INT NOT NULL DEFAULT 0,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_refund_no` (`refund_no`),
    UNIQUE KEY `uk_refund_business_key` (`business_key`),
    KEY `idx_refund_order_time` (`order_id`, `create_time`),
    KEY `idx_refund_retry` (`status`, `next_retry_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全额退款交易';

CREATE TABLE `user_notification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `event_id` VARCHAR(64) NOT NULL,
    `business_key` VARCHAR(128) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `type` VARCHAR(32) NOT NULL,
    `title` VARCHAR(100) NOT NULL,
    `content` VARCHAR(500) NOT NULL,
    `order_id` BIGINT DEFAULT NULL,
    `read_at` DATETIME DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_notification_event` (`event_id`),
    UNIQUE KEY `uk_notification_business_key` (`business_key`),
    KEY `idx_notification_user_cursor` (`user_id`, `id`),
    KEY `idx_notification_retention` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户持久化通知';

CREATE TABLE `outbox_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `event_id` VARCHAR(64) NOT NULL,
    `business_key` VARCHAR(128) NOT NULL,
    `aggregate_type` VARCHAR(32) NOT NULL,
    `aggregate_id` VARCHAR(64) NOT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `payload_json` TEXT NOT NULL,
    `status` VARCHAR(16) NOT NULL,
    `attempt_count` INT NOT NULL DEFAULT 0,
    `next_attempt_at` DATETIME NOT NULL,
    `published_at` DATETIME DEFAULT NULL,
    `last_error` VARCHAR(500) DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_outbox_event_id` (`event_id`),
    UNIQUE KEY `uk_outbox_business_event` (`business_key`, `event_type`),
    KEY `idx_outbox_publish` (`status`, `next_attempt_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠通知发件箱';
