sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: ##
    access-key-id: ##
    access-key-secret: ##
    bucket-name: ##
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx97c3724defa2be41
    secret: 9960c7712f3a82d068aa14121671d939
